spring:
  application:
    name: wishlist
  security:
    user:
      name: ${WISHLIST_USERNAME}
      password: ${WISHLIST_PASSWORD}

wishlist:
  title: ${WISHLIST_TITLE}
  markdown-path: ${WISHLIST_MARKDOWN-PATH}
  custom-css-dir: ${WISHLIST_CUSTOM-CSS-DIR:}
  custom-css-cache-period: ${WISHLIST_CUSTOM-CSS-CACHE-PERIOD:}
  custom-fav-icon: ${WISHLIST_CUSTOM-FAV-ICON:}