WISHLIST_USERNAME: noah
WISHLIST_PASSWORD: password
WISHLIST_TITLE: wishlist
WISHLIST_MARKDOWN-PATH: /home/noah/temp/file.md
WISHLIST_CUSTOM-CSS-DIR:
WISHLIST_CUSTOM-CSS-CACHE-PERIOD: 3600
WISHLIST_CUSTOM-FAV-ICON: